language: php
php:
  - 7.3
  - 7.4
before_script:
  - composer self-update
  - composer install
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
