language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
matrix:
    allow_failures:
        - php: nightly
script:
  - phpunit -c tests/unit/ --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
