<?php
/**
 * 
 * This file is part of Aura for PHP.
 * 
 * @package Aura.Cli
 * 
 * @license http://opensource.org/licenses/bsd-license.php BSD
 * 
 */
namespace Aura\Cli\Context;

/**
 * 
 * A read-only representation of values values.
 * 
 * @package Aura.Cli
 * 
 */
class GetoptValues extends GlobalValues
{
    /**
     * 
     * An array of exceptions generated by parsing errors.
     * 
     * @var array
     * 
     */
    protected $errors;
    
    /**
     * 
     * Constructor.
     * 
     * @param array $values The values values to be represented by this array.
     * 
     * @param array $errors Errors generated while parsing.
     * 
     */
    public function __construct(array $values = [], array $errors = [])
    {
        parent::__construct($values);
        $this->errors = $errors;
    }
    
    /**
     * 
     * Does this values object have any errors?
     * 
     * @return bool
     * 
     */
    public function hasErrors()
    {
        return (bool) $this->errors;
    }
    
    /**
     * 
     * Returns the array of exceptions generated by parsing errors.
     * 
     * @return array
     * 
     */
    public function getErrors()
    {
        return $this->errors;
    }
}
